version: "3"
services:
    postgres:
        image: postgres:14.1-alpine
        container_name: postgres
        hostname: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test_welbex
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
            - postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        restart: unless-stopped

    prisma-app:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: prisma-api
        environment:
            DATABASE_URL: postgresql://postgres:root@postgres:5432/test_welbex?schema=public
        depends_on:
            - postgres
        ports:
            - "3000:3000"
        restart: always

volumes:
    postgres-data:
    pgadmin-data:
